---
title: "20221117-webinar_attendees-jsg2145"
author: "Jared Garfinkel"
date: '2022-11-17'
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
library(RSelenium)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
# url = "https://authentication.logmeininc.com/login?service=https%3A%2F%2Fauthentication.logmeininc.com%2Foauth%2Fapprove%3Fclient_id%3Ddc09563b-c2f3-4156-8d5c-4747b8bdf2ad%26response_type%3Dtoken%26redirect_uri%3Dhttps%253A%252F%252Fdashboard.gotowebinar.com%252Fauthenticate.html%26state%3D%257B%2522path%2522%253A%2522https%253A%252F%252Fdashboard.gotowebinar.com%252F%2522%257D%26login_theme%3Dg2w&theme=g2w"

url2 = "https://dashboard.gotowebinar.com/"
```

### RSelenium

```{r}
remDr <- RSelenium::remoteDriver(remoteServerAddr = "localhost",
                                 port = 4445L,
                                 browserName = "chrome")
remDr$open()
```

```{r}
remDr$navigate(url2)
remDr$screenshot(display = TRUE) # login form
```

#### login

##### Enter Email

```{r}
email = remDr$findElement(using = "css", value= "#emailAddress")
email$sendKeysToElement(list("maia.c@nymc.org"))
# Next Button
next_b <- remDr$findElement(using = "css", "#next-button")
next_b$clickElement()
```

##### Enter Password

```{r}
pw = remDr$findElement(using = "css", value= "#password")
pw$sendKeysToElement(list("NyMc6809!!"))
# Submit
submit_b <- remDr$findElement(using = "css", "#submit")
submit_b$clickElement()
```

#### Go to the Analytics Web Page

```{r}
remDr$navigate("https://analytics.gotowebinar.com/analytics/sessions")
# remDr$screenshot(display = TRUE) # analytics page, check
```

#### Click the most recent webinar

"Fall Series"

##### Extract the names of the webinars

```{r, eval = FALSE, include = FALSE}
past_webinars = remDr$findElements(using = "css", ".stickyName a")
# output = NULL
# for (i in 1:length(past_webinars)) {
#   output[[i]] = past_webinars$getElementText()[[i]]
# }

names = map(past_webinars, ~.$getElementText()[[1]]) # list of webinars, check
# past_webinars$getElementText()[[1]]
```

###### Example of a link click

```{r}
webinar1 = remDr$findElement(using = "css", value = ".rt-tr-group:nth-child(1) a")
webinar1$clickElement()
# remDr$screenshot(display = TRUE) # most recent webinar, check
# body_content = remDr$findElement(using = "css", value = ".contentBody")
# page_text = body_content$getElementText()[[1]] %>% 
#   str_split("\\n")
# 
# length(page_text[[1]]) # 574 entries, 1st page only
  
```

###### Do something (grab emails)

```{r}
webinar1_email_obj = remDr$findElements(using = "css", value = ".rt-td a")
webinar_email_list = map(webinar1_email_obj, ~.$getElementText()[[1]])
webinar_email_list
```


###### Click the next tab of the webinar attendees

```{r}
tabs = remDr$findElements(using = "css", value = ".styles__page-link___3Vvj-")
tab_names = map(tabs, ~ .$getElementText()[[1]])
tab_names
tabs[[3]]$clickElement()
webinar1_email_obj2 = remDr$findElements(using = "css", value = ".rt-td a")
webinar_email_list2 = map(webinar1_email_obj2, ~.$getElementText()[[1]])
head(webinar_email_list2)
head(webinar_email_list)
# remDr$goBack()
# remDr$screenshot(display=TRUE)
```


##### list only the desired webinars

```{r}
past_webinars[[1]]$clickElement()
past_webinars[[1]]$screenshot(display=TRUE)

for(i in 1:length(webinars)){
    webinars[[i]]$clickElement()
    Sys.sleep(2)
    #do something and go back to previous page
    driver$goBack()
    Sys.sleep(1)
    # refresh the elements
    elements <- driver$findElements(using = "css",".nav-list ul a")
}
```


```{r}
webinar = NULL
for (i in 1:length(remDr$findElements(using = "css", ".stickyName a"))) {
  if ((remDr$findElements(using = "css", ".stickyName a")$getElementText()[[1]]) == "NYMC Homebuyer Education Webinar (Fall Series)") {
    webinar[[i]] = remDr$findElement(using = "css", paste0(".rt-tr-group:nth-child(", i, ") a"))
  }
}

webinar1 = remDr$findElement(using = "css", ".rt-tr-group:nth-child(1) a")
webinar1$getElementText()[[1]]

webinar1$clickElement()
webinar1$screenshot(display=TRUE)

map(webinar, ~.$getElementText()[[1]])
webinar[[1]]$getElementText()[[1]]
webinar[[1]]$clickElement()
```




### rvest

```{r}
sess = session(url)
sess
```

```{r}
form = html_form(sess)[[1]]
# str(form)
filled_form = html_form_set(form, 
                emailAddress = "maia.c@nymc.org",
                password = "NyMc6809!!")
session_submit(sess, filled_form)
# submit_form()
```

```{r}
sess_a = sess %>% 
  session_jump_to("https://analytics.gotowebinar.com/analytics/sessions")
# sess_a
```

```{r}
html = read_html(sess_a)

html %>% 
  html_elements("body") %>% 
  html_text2()

rD = RSelenium::remoteDriver(browser = "chrome")
remDr = rD[["client"]]
remDr$navigate(url)
remDr$open()

head(remDr$sessionInfo)
```


```{r}
sess_a %>%
  html_element("a") %>% 
  html_text()
```



